id: ftb_693226878d58638a
display_name: "Climbing the Ranks"
chapters:
  - STEAM_AGE
  - LV_LOW_VOLTAGE
  - MV_MEDIUM_VOLTAGE
  - HV_HIGH_VOLTAGE
  - EV_EXTREME_VOLTAGE
  - IV_INSANE_VOLTAGE
  - LUV_LUDICROUS_VOLTAGE
  - ZPM_ZERO_POINT_MODULE
  - UV_ULTIMATE_VOLTAGE
